name = "ycu-judo"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"

kv_namespaces = [
  { binding = "PLAYLISTS", id = "90746471c82048a595ca4728b8a4fc0b", preview_id = "8c16d4369ecb43aaaf3e2f4e5b21038a" }
]

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[miniflare]
  kv_persist = true

[wasm_modules]
  # JPEG_ENC_WASM = "node_modules/remix-image-wasm/jpeg_enc.wasm"
  JPEG_DEC_WASM = "node_modules/remix-image-wasm/jpeg_dec.wasm"
  PNG_WASM = "node_modules/remix-image-wasm/png.wasm"
  WEBP_ENC_WASM = "node_modules/remix-image-wasm/webp_enc.wasm"
  # WEBP_DEC_WASM = "node_modules/remix-image-wasm/webp_dec.wasm"
  # AVIF_ENC_WASM = "node_modules/remix-image-wasm/avif_enc.wasm"    # uncomment for AVIF support
  # AVIF_DEC_WASM = "node_modules/remix-image-wasm/avif_dec.wasm"    # uncomment for AVIF support
